require 'burn/fuel/dsl_base'
require 'burn/fuel/rom/sound_effect'
require 'burn/fuel/rom/note'
require 'burn/fuel/rom/channel_stream'
require 'burn/fuel/rom/declare'
require 'burn/fuel/rom/sound'
require 'burn/fuel/rom/music'
require 'burn/fuel/rom/scene'

require 'burn/fuel/telnet/declare'
require 'burn/fuel/telnet/scene'