#!/bin/bash
BURN_ROOT="$(cd $(dirname $0);pwd)/.."
export PATH="$PATH:${BURN_ROOT}/cc65/bin"
export CC65_HOME="${BURN_ROOT}/cc65"
cc65 -Oi "${1}/main.c" --add-source -I "${1}/asset/"
if [ "$?" -ne 0 ]; then
  echo "[cc65] Failed to compile c program generated by burn"
  exit 1
fi
ca65 -I "${1}/asset/" "${1}/asset/crt0.s"
if [ "$?" -ne 0 ]; then
  echo "[ca65] Failed to assemble crt0.s"
  exit 1
fi
ca65 -I "${1}/asset/" "${1}/main.s"
if [ "$?" -ne 0 ]; then
  echo "[ca65] Failed to assemble main.s"
  exit 1
fi
ca65 -I "${1}/asset/" "${1}/asset/music.s"
if [ "$?" -ne 0 ]; then
  echo "[ca65] Failed to assemble music.s"
  exit 1
fi
ld65 -L "${1}/asset/"  -C "${1}/asset/nes.cfg" -o "${1}/main.out" "${1}/asset/crt0.o" "${1}/main.o" "${1}/asset/runtime.lib" "${1}/asset/music.o"
if [ "$?" -ne 0 ]; then
  echo "[ld65] Failed to link objects"
  exit 1
fi
exit 0