set BURN_ROOT=%~dp0..
path %PATH%;%BURN_ROOT%\cc65\bin\;
set CC65_HOME=%BURN_ROOT%\cc65
cc65 -Oi %1\main.c --add-source -I %1\asset\
if not "%ERRORLEVEL%"  == "0" (
	echo [cc65] Failed to compile c program generated by burn
	EXIT /b 1
)
ca65 -I %1\asset\ %1\asset\crt0.s
if not "%ERRORLEVEL%"  == "0" (
	echo [ca65] Failed to assemble crt0.s
	EXIT /b 1
)
ca65 -I %1\asset\ %1\main.s
if not "%ERRORLEVEL%"  == "0" (
	echo [ca65] Failed to assemble main.s
	EXIT /b 1
)
ca65 -I %1\asset\ %1\asset\music.s
if not "%ERRORLEVEL%"  == "0" (
	echo [ca65] Failed to assemble music.s
	EXIT /b 1
)
ld65 -L %1\asset\ -C %1\asset\nes.cfg -o %1\main.out %1\asset\crt0.o %1\main.o %1\asset\runtime.lib %1\asset\music.o
if not "%ERRORLEVEL%"  == "0" (
	echo [ld65] Failed to link objects
	EXIT /b 1
)
IF ERRORLEVEL 1 EXIT /b 1
EXIT /b 0
